DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS BOOK;

CREATE TABLE GENRE (
	  GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
	  GENRE VARCHAR(250) NOT NULL UNIQUE,
	  DESCRIPTION VARCHAR(250) NOT NULL,
      PRIMARY KEY (GENRE_ID)
 );
 
 CREATE TABLE BOOK (
    BOOK_ID INTEGER NOT NULL AUTO_INCREMENT,
	GENRE_ID INTEGER NOT NULL,
    TITLE VARCHAR(250) NOT NULL,
	AUTHOR VARCHAR(250) NOT NULL,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
);